// <auto-generated />
using HeartifyDating.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeartifyDating.Infrastructure.Migrations
{
    [DbContext(typeof(HeartifyDatingDbContext))]
    [Migration("20240201091540_PersonProfileDone")]
    partial class PersonProfileDone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeartifyDating.Infrastructure.Data.Models.PersonProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Person Unique Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("Person Age");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Person Description");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Person First Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Person Last Name");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Person Profile Picture");

                    b.Property<string>("RandomPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Person Random Picture");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Wanted Relationship Type");

                    b.Property<string>("Sexuality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Person Sexual Orientation");

                    b.Property<string>("UsernamePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Person Username Picture");

                    b.Property<string>("WantedSexuality")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Seuxal Orientation of Wanted Person");

                    b.HasKey("Id");

                    b.ToTable("PersonProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
